clc;

disp(['TrainSize: ' num2str(Results.length_tra) ...
      ' ValidationSize: ' num2str(Results.length_val) ...
      ' TestSize: ' num2str(length(Results.idx_test))]);

disp(['Test No. ' num2str(Results.testSubject)...
    ', TRAIN - RMSE: ' num2str(Results.indicator_tra.rmse, '%.4f') ...
    '， R2: ' num2str(Results.indicator_tra.R2, '%.4f') ...
    '， bias: ' num2str(Results.indicator_tra.bias, '%.4f') ...
    '， 95CI%: [' num2str(Results.indicator_tra.LoA_lower, '%.4f') ', ' num2str(Results.indicator_tra.LoA_upper, '%.4f') ']' ]);

disp(['Test No. ' num2str(Results.testSubject)...
    ', TEST - RMSE: ' num2str(Results.indicator_tes.rmse, '%.4f') ...
    '， R2: ' num2str(Results.indicator_tes.R2, '%.4f') ...
    '， bias: ' num2str(Results.indicator_tes.bias, '%.4f') ...
    '， 95CI%: [' num2str(Results.indicator_tes.LoA_lower, '%.4f') ', ' num2str(Results.indicator_tes.LoA_upper, '%.4f') ']' ]);
